# -*- coding: utf-8 -*-

specialties_dict = {
1: 'Acupuntura',
2: 'Alergia e Imunologia',
3: 'Anestesiologia',
4: 'Angiologia',
5: 'Cancerologia',
6: 'Cardiologia',
7: 'Cirurgia Cardiovascular',
8: 'Cirurgia da Mão',
9: 'Cirurgia de Cabeça e Pescoço',
10: 'Cirurgia do Aparelho Digestivo',
11: 'Cirurgia Geral',
12: 'Cirurgia Pediátrica',
13: 'Cirurgia Plástica',
14: 'Cirurgia Torácica',
15: 'Cirurgia Vascular',
16: 'Clínica Médica',
17: 'Coloproctologia',
18: 'Dermatologia',
19: 'Endocrinologia e Metabologia',
20: 'Endoscopia',
21: 'Gastroenterologia',
22: 'Genética Médica',
23: 'Geral',
24: 'Geriatria',
25: 'Ginecologia e Obstetrícia',
26: 'Hematologia e Hemoterapia',
27: 'Homeopatia',
28: 'Infectologia',
29: 'Mastologia',
30: 'Medicina de Família e Comunidade',
31: 'Medicina do Trabalho',
32: 'Medicina de Tráfego',
33: 'Medicina Esportiva',
34: 'Medicina Física e Reabilitação',
35: 'Medicina Intensiva',
36: 'Medicina Legal e Perícia Médica',
37: 'Medicina Nuclear',
38: 'Medicina Preventiva e Social',
39: 'Nefrologia',
40: 'Neurocirurgia',
41: 'Neurologia',
42: 'Nutrologia',
43: 'Oftalmologia',
44: 'Ortopedia e Traumatologia',
45: 'Otorrinolaringologia',
46: 'Patologia',
47: 'Patologia Clínica/Medicina Laboratorial',
48: 'Pediatria',
49: 'Pneumologia',
50: 'Psiquiatria',
51: 'Radiologia e Diagnóstico por Imagem',
52: 'Radioterapia',
53: 'Reumatologia',
54: 'Urologia'}

specialties = specialties_dict.values()

states_dict = {
'AC': 'Acre',
'AL': 'Alagoas',
'AP': 'Amapá',
'AM': 'Amazonas',
'BA': 'Bahia',
'CE': 'Ceará',
'DF': 'Distrito Federal',
'ES': 'Espírito Santo',
'GO': 'Goiás',
'MA': 'Maranhão',
'MT': 'Mato Grosso',
'MS': 'Mato Grosso do Sul',
'MG': 'Minas Gerais',
'PA': 'Pará',
'PB': 'Paraíba',
'PR': 'Paraná',
'PE': 'Pernambuco',
'PI': 'Piauí',
'RJ': 'Rio de Janeiro',
'RN': 'Rio Grande do Norte',
'RS': 'Rio Grande do Sul',
'RO': 'Rondônia',
'RR': 'Roraima',
'SC': 'Santa Catarina',
'SP': 'São Paulo',
'SE': 'Sergipe',
'TO': 'Tocantins'
}

logradouro_dict = {
'Aeroporto': 'Aeroporto',
'Alameda': 'Alameda',
'Área': 'Área',
'Avenida': 'Avenida',
'Campo': 'Campo',
'Chácara': 'Chácara',
'Colônia': 'Colônia',
'Condomínio': 'Condomínio',
'Conjunto': 'Conjunto',
'Distrito': 'Distrito',
'Esplanada': 'Esplanada',
'Estação': 'Estação',
'Estrada': 'Estrada',
'Favela': 'Favela',
'Fazenda': 'Fazenda',
'Feira': 'Feira',
'Jardim': 'Jardim',
'Ladeira': 'Ladeira',
'Lago': 'Lago',
'Lagoa': 'Lagoa',
'Largo': 'Largo',
'Loteamento': 'Loteamento',
'Morro': 'Morro',
'Núcleo': 'Núcleo',
'Parque': 'Parque',
'Passarela': 'Passarela',
'Pátio': 'Pátio',
'Praça': 'Praça',
'Quadra': 'Quadra',
'Recanto': 'Recanto',
'Residência': 'Residência',
'Rodovia': 'Rodovia',
'Rua': 'Rua',
'Setor': 'Setor',
'Sítio': 'Sítio',
'Travessa': 'Travessa',
'Trecho': 'Trecho',
'Trevo': 'Trevo',
'Vale': 'Vale',
'Vereda': 'Vereda',
'Via': 'Via',
'Viadulto': 'Viadulto',
'Viela': 'Viela',
'Vila': 'Vila'}
